CREATE DATABASE mydb;
GRANT ALL PRIVILEGES ON mydb.* TO 'myuser'@'%' IDENTIFIED BY 'mysql';
GRANT ALL PRIVILEGES ON mydb.* TO 'myuser'@'localhost' IDENTIFIED BY 'mysql';
USE mydb
CREATE TABLE BOOKS(
ID int NOT NULL PRIMARY KEY,
TITLE  VARCHAR(200) NOT NULL,
AUTHOR  VARCHAR(200) NOT NULL,
PRICE FLOAT(24) NOT NULL
);
CREATE TABLE sell(
ID int NOT NULL PRIMARY KEY,

BUYER  VARCHAR(200) NOT NULL,
PRICE FLOAT(24) NOT NULL,
DISCOUNT FLOAT(24) NOT NULL,
ISCLUBMEMBER BOOL
);
